name: Preview
on:
  push:
    branches:
      - dev
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.18.3
          registry-url: https://registry.npmjs.org/
      - name: Build
        run: |
          yarn
          yarn preview
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist